# .github/workflows/gradle-build-pr.yml
name: Run Gradle Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-8@3.1
